# This is a basic workflow to help you get started with Actions
name: Deploy Infra

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run Bicep Linter
          run: az bicep build --file ./deploy/main.bicep
    validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: azure/login@v1
          name: Login to Azure
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}            
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - uses: azure/arm-deploy@v1
          name: Run preflight validation
          with:
            deploymentName: ${{ github.run_number}}
            resourceGroupName: ${{ secrets.AZURE_RG_NAME }}
            template: ./deploy/main.bicep
            parameters: ./deploy/parameters.prod.json
            deploymentMode: 'Validate4'
            

