# This is a basic workflow to help you get started with Actions
name: Deploy Infra

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run Bicep Linter
          run: az bicep build --file ./deploy/main.bicep